services:
  postgres:
    container_name: elasticsearch-training-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elasticsearch-training
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  api:
    container_name: elasticsearch-training-api
    image: elasticsearch-training-api
    build:
      context: .
    expose:
      - "8080"
    env_file:
      - .env
    volumes:
      - ./config/app.dev.yaml:/app/config/app.dev.yaml:ro
      - ./db/migrations:/app/db/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_started

  nginx:
    container_name: elasticsearch-training-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  pg_volume: