server:
  http_port: 8080
postgres:
  pg_host: "postgres"
  pg_port: 5432
  pg_user: "postgres"
  pg_password: "your_password"
  pg_name: "elastic"
  pg_sslmode: "disable"
elastic:
  es_host: "elasticsearch"
  es_port: 9200
